return {
	-- player events
	OnAttack = "OnAttack",
	OnLeftRight = "OnLeftRight",
	OnUpDown ="OnUpDown",

	SetGameState = "SetGameState",
	GetPlayer = "GetPlayer",
	GetEnemy = "GetEnemy",
    GetTile = "GetTile",
    ModifyCoinAmount = "ModifyCoinAmount",
    AddCards = "AddCards",
    SetAnimationEnabled = "SetAnimationEnabled",
    ShowUiCanvas = "ShowUiCanvas",

    OnCardDiscarded = "OnCardDiscarded",
    OnCardUsed = "OnCardUsed",
    OnSetEnemies = "OnSetEnemies",
    OnSetEnemy = "OnSetEnemy",
    OnRevealTile = "OnRevealTile",
    OnEnterTile = "OnEnterTile",
    OnSetPlayerCard = "OnSetPlayerCard",
    OnTakeDamage = "OnTakeDamage",
    OnEnemyDefeated = "OnEnemyDefeated",
    OnEnterCombat = "OnEnterCombat",
    OnExitCombat = "OnExitCombat",
    OnPauseChanged = "OnPauseChanged",
    OnUpdateCoinsAmount = "OnUpdateCoinsAmount",
    OnUpdateCardsAmount = "OnUpdateCardsAmount",
    OnUpdateCardDeckAmount = "OnUpdateCardDeckAmount",
    OnUpdateCardDiscardsAmount = "OnUpdateCardDiscardsAmount",
    OnUpdateTimeRemaining = "OnUpdateTimeRemaining",
    OnUpdateTimeRemainingString = "OnUpdateTimeRemainingString",
    OnUpdateWeaknessAmount = "OnUpdateWeaknessAmount",
    OnUpdateTotalCoinsCollected = "OnUpdateTotalCoinsCollected",
    OnUpdateTotalCardsCollected = "OnUpdateTotalCardsCollected",
    OnUpdateTotalEnemiesDefeated = "OnUpdateTotalEnemiesDefeated",
    OnUpdateTotalTimeLeft = "OnUpdateTotalTimeLeft",
    OnTimerFinished = "OnTimerFinished",
	OnQuitPressed = "OnQuitPressed",
	OnOKPressed = "OnOKPressed",
	OnMenuPressed = "OnMenuPressed",
	OnNewGamePressed = "OnNewGamePressed",
	OnResumePressed = "OnResumePressed",
	OnRetryPressed = "OnRetryPressed",
	OnNextLevelPressed = "OnNextLevelPressed",
	OnRunAway = "OnRunAway",
    OnUseCard = "OnUseCard",
    OnDiscard = "OnDiscard",
    OnSetEnemyCardVisible = "OnSetEnemyCardVisible",
    OnSetPlayerCardsVisible = "OnSetPlayerCardsVisible"
}